#!/bin/sh
set -eu
if (set -o pipefail) 2>/dev/null; then
	set -o pipefail
fi

main() {
    # generated by GPT-5.3-Codex
	rm -rf dist dist.tar.zst
	mkdir -p dist

	# 递归复制 src/ 下内容到 dist/
	cp -a src/. dist/

	# 将 dist/ 下所有 .svg 压缩为 .svgz，并删除原始 .svg
	find dist -type f -name '*.svg' -print0 |
		while IFS= read -r -d '' svg_file; do
			svgz_file="${svg_file%.svg}.svgz"
			gzip -n -9 -c "$svg_file" >"$svgz_file"
			rm -f "$svg_file"
		done

	# 打包整个 dist 目录为 zstd 压缩包
	tar --zstd -cf dist.tar.zst dist
}

main "$@"
